fix monetary_sanction
THEOLEX-IO/legal_doc_processing pull request #41
Opened 2021-07-31 00:45 UTC by chaalia

2021-07-31 07:41 UTC, JawadRouen commented
Hello @chaalia did you add a new unit test to confirm this correction  ?
it means, this new unit test sould fail without you correction and succeed after your correction

FYI @AlexandreGazagnes

2021-07-31 07:43 UTC, JawadRouen requested changes

2021-07-31 07:43 UTC, JawadRouen commented on legal_doc_processing/press_release/monetary_sanction/predict.py
> +    # import pdb;pdb.set_trace()
clean pdb

2021-09-02 11:44 UTC, AlexandreGazagnes commented
@sokharsamb -> verifier pour demain que pas d'erreur sur monetray_sanction, pas sur la partie valeur, mais sur le type ou un raise error

accepte les données incohérentes mais on veut un retour valide de la fonction de pred

2021-09-03 10:47 UTC, sokharsamb commented
Pas de raise error par contre y'a des donnees qui sont de type int d'autres de type str.
From @AlexandreGazagnes forcer retour string.
@sokharsamb  Ajouter str avant le retour de la fonction

2021-09-06 09:36 UTC, sokharsamb commented
A @AlexandreGazagnes 
 Tout est en type str maintenant.

2021-09-08 10:48 UTC, closed without merging